server:
  port: 9011
spring:
  application:
    name: tensquare-manager
jwt:
  config:
    key: itcast
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    tensquare-base:
      path: /base/**
      serviceId: tensquare-base
    tensquare-qa:
      path: /qa/**
      serviceId: tensquare-qa
    tensquare-user:
      path: /user/**
      serviceId: tensquare-user